export const avatars= [
    { avatarId: 1,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736009684/1_mb3vot.png',
      altText: 'Smiling red-haired girl',
  },
  { avatarId: 2,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736009684/2_ystygx.png',
      altText: 'Curious dark-haired girl',
  }, 
  { avatarId: 3,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736009685/3_akbeuq.png',
      altText: 'Shy girl behind fence',
  },
  { avatarId: 4,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736009685/4_xszu1f.png',
      altText: 'Smiling light-haired boy',
  },
  { avatarId: 5,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736009684/5_kg8x71.png',
      altText: 'Bashful curly-haired boy',
  },
  { avatarId: 6,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736009685/6_x6uvul.png',
      altText: 'Playful blonde-haired girl',
  },
  { avatarId: 7,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736009682/7_ojhweo.png',
      altText: 'Smiling boy leaning on wall',
  },
  { avatarId: 8,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736009688/8_t0ip39.png',
      altText: 'Happy girl behind tree',
  },
  { avatarId: 9,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736009688/9_potwrk.png',
      altText: 'Curly-haired girl behind fence',
  },
  { avatarId: 10,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011048/10_pmoh9h.png',
      altText: 'Playful curly-haired boy',
  },
  { avatarId: 11,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736009686/11_jnbhfy.png',
      altText: 'Shy girl in window',
  },
  { avatarId: 12,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736009688/12_uxwqkc.png',
      altText: 'Child hiding behind brick wall',
  },
  { avatarId: 13,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011080/13_fb3mio.png',
      altText: 'Chickens in garden',
  },
  { avatarId: 14,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011081/14_cf6eq8.png',
      altText: 'Hiker near mushroom forest',
  },
  { avatarId: 15,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011081/15_nprdjd.png',
      altText: 'Pale beige mushrooms',
  },
  { avatarId: 16,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011081/16_o2kjre.png',
      altText: 'Birds around birdbath',
  },
  { avatarId: 17,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011082/17_xluxfn.png',
      altText: 'Bountiful kitchen with shelf',
  },
  { avatarId: 18,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011081/18_aamy1d.png',
      altText: 'Shelves of preserves and jam',
  },
  { avatarId: 19,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011082/19_yzwxdf.png',
      altText: 'Cabin with field beneath the moon',
  },
  { avatarId: 20,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011082/20_jmjtq3.png',
      altText: 'Cat in the flowers',
  },
  { avatarId: 21,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011083/21_jnvjlh.png',
      altText: 'Cottage surrounded by wildflowers',
  },
  { avatarId: 22,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011083/22_wd0yuj.png',
      altText: 'Cottage with garden',
  },
  { avatarId: 23,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011084/23_ypaojq.png',
      altText: 'Dog with flowers',
  },
  { avatarId: 24,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011085/24_jxrzot.png',
      altText: 'Lone person walking towards a cottage',
  },
  { avatarId: 25,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011084/25_ilbyth.png',
      altText: 'Colorful vegetables',
  },
  { avatarId: 26,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011085/26_nltlu9.png',
      altText: 'Fresh bread by the window',
  },
  { avatarId: 27,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011085/27_otoysa.png',
      altText: 'Stack of books',
  },
  { avatarId: 28,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011085/28_q27ihg.png',
      altText: 'A person gardening',
  },
  { avatarId: 29,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011087/29_b8k0xi.png',
      altText: 'Mushroom cottage',
  },
  { avatarId: 30,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011086/30_offsp8.png',
      altText: 'Table with bread and oranges',
  },
  { avatarId: 31,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011091/31_wri6ax.png',
      altText: 'Cottage with pond',
  },
  { avatarId: 32,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011086/32_k8onyy.png',
      altText: 'View from a kitchen window',
  },
  { avatarId: 33,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011086/33_rsha1a.png',
      altText: 'Basket of pink flowers',
  },
  { avatarId: 34,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011087/34_ihlbum.png',
      altText: 'Cottage with pink flowers',
  },
  { avatarId: 35,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011089/35_cpizwx.png',
      altText: 'Cozy home library',
  },
  { avatarId: 36,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011088/36_stxxrv.png',
      altText: 'Beekeeper and beehive',
  },
  { avatarId: 37,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011089/37_ceyvjm.png',
      altText: 'Bicyclist on road with flowers',
  },
  { avatarId: 38,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011089/38_kpwhaa.png',
      altText: 'Tea party table',
  },
  { avatarId: 39,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011091/39_mlidji.png',
      altText: 'Cat in window',
  },
  { avatarId: 40,
      avatarSrc: 'https://res.cloudinary.com/davmzu0ic/image/upload/v1736011090/40_pczc5g.png',
      altText: 'Starry night cottage',
  }
];