export const avatars= [
    { avatarId: 1,
      avatarSrc: '/assets/avatars/1.png',
      altText: 'Smiling red-haired girl',
  },
  { avatarId: 2,
      avatarSrc: '/assets/avatars/2.png',
      altText: 'Curious dark-haired girl',
  }, 
  { avatarId: 3,
      avatarSrc: '/assets/avatars/3.png',
      altText: 'Shy girl behind fence',
  },
  { avatarId: 4,
      avatarSrc: '/assets/avatars/4.png',
      altText: 'Smiling light-haired boy',
  },
  { avatarId: 5,
      avatarSrc: '/assets/avatars/5.png',
      altText: 'Bashful curly-haired boy',
  },
  { avatarId: 6,
      avatarSrc: '/assets/avatars/6.png',
      altText: 'Playful blonde-haired girl',
  },
  { avatarId: 7,
      avatarSrc: '/assets/avatars/7.png',
      altText: 'Smiling boy leaning on wall',
  },
  { avatarId: 8,
      avatarSrc: '/assets/avatars/8.png',
      altText: 'Happy girl behind tree',
  },
  { avatarId: 9,
      avatarSrc: '/assets/avatars/9.png',
      altText: 'Curly-haired girl behind fence',
  },
  { avatarId: 10,
      avatarSrc: '/assets/avatars/10.png',
      altText: 'Playful curly-haired boy',
  },
  { avatarId: 11,
      avatarSrc: '/assets/avatars/11.png',
      altText: 'Shy girl in window',
  },
  { avatarId: 12,
      avatarSrc: '/assets/avatars/12.png',
      altText: 'Child hiding behind brick wall',
  },
  { avatarId: 13,
      avatarSrc: '/assets/avatars/13.png',
      altText: 'Chickens in garden',
  },
  { avatarId: 14,
      avatarSrc: '/assets/avatars/14.png',
      altText: 'Hiker near mushroom forest',
  },
  { avatarId: 15,
      avatarSrc: '/assets/avatars/15.png',
      altText: 'Pale beige mushrooms',
  },
  { avatarId: 16,
      avatarSrc: '/assets/avatars/16.png',
      altText: 'Birds around birdbath',
  },
  { avatarId: 17,
      avatarSrc: '/assets/avatars/17.png',
      altText: 'Bountiful kitchen with shelf',
  },
  { avatarId: 18,
      avatarSrc: '/assets/avatars/18.png',
      altText: 'Shelves of preserves and jam',
  },
  { avatarId: 19,
      avatarSrc: '/assets/avatars/19.png',
      altText: 'Cabin with field beneath the moon',
  },
  { avatarId: 20,
      avatarSrc: '/assets/avatars/20.png',
      altText: 'Cat in the flowers',
  },
  { avatarId: 21,
      avatarSrc: '/assets/avatars/21.png',
      altText: 'Cottage surrounded by wildflowers',
  },
  { avatarId: 22,
      avatarSrc: '/assets/avatars/22.png',
      altText: 'Cottage with garden',
  },
  { avatarId: 23,
      avatarSrc: '/assets/avatars/23.png',
      altText: 'Dog with flowers',
  },
  { avatarId: 24,
      avatarSrc: '/assets/avatars/24.png',
      altText: 'Lone person walking towards a cottage',
  },
  { avatarId: 25,
      avatarSrc: '/assets/avatars/25.png',
      altText: 'Colorful vegetables',
  },
  { avatarId: 26,
      avatarSrc: '/assets/avatars/26.png',
      altText: 'Fresh bread by the window',
  },
  { avatarId: 27,
      avatarSrc: '/assets/avatars/27.png',
      altText: 'Stack of books',
  },
  { avatarId: 28,
      avatarSrc: '/assets/avatars/28.png',
      altText: 'A person gardening',
  },
  { avatarId: 29,
      avatarSrc: '/assets/avatars/29.png',
      altText: 'Mushroom cottage',
  },
  { avatarId: 30,
      avatarSrc: '/assets/avatars/30.png',
      altText: 'Table with bread and oranges',
  },
  { avatarId: 31,
      avatarSrc: '/assets/avatars/31.png',
      altText: 'Cottage with pond',
  },
  { avatarId: 32,
      avatarSrc: '/assets/avatars/32.png',
      altText: 'View from a kitchen window',
  },
  { avatarId: 33,
      avatarSrc: '/assets/avatars/33.png',
      altText: 'Basket of pink flowers',
  },
  { avatarId: 34,
      avatarSrc: '/assets/avatars/34.png',
      altText: 'Cottage with pink flowers',
  },
  { avatarId: 35,
      avatarSrc: '/assets/avatars/35.png',
      altText: 'Cozy home library',
  },
  { avatarId: 36,
      avatarSrc: '/assets/avatars/36.png',
      altText: 'Beekeeper and beehive',
  },
  { avatarId: 37,
      avatarSrc: '/assets/avatars/37.png',
      altText: 'Bicyclist on road with flowers',
  },
  { avatarId: 38,
      avatarSrc: '/assets/avatars/38.png',
      altText: 'Tea party table',
  },
  { avatarId: 39,
      avatarSrc: '/assets/avatars/39.png',
      altText: 'Cat in window',
  },
  { avatarId: 40,
      avatarSrc: '/assets/avatars/40.png',
      altText: 'Starry night cottage',
  }
];